// <auto-generated />
namespace IssmaRequiredList.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class DeletedIsAliveColumn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DeletedIsAliveColumn));
        
        string IMigrationMetadata.Id
        {
            get { return "202003062133589_DeletedIsAliveColumn"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
